/**
 * SolarSystemConfig.ts
 * Comprehensive NASA/IAU astronomical datasets for the Solar System.
 * Contains the Sun, 8 planets, 18 major moons, 5 dwarf planets, asteroid/Kuiper belts, and comets.
 */

import type {
  CelestialBody,
  AsteroidBeltConfig,
  KuiperBeltConfig,
  CometTrajectory,
} from './SolarSystemTypes';

// ── 1. The Sun ───────────────────────────────────────────────────────────────

export const SUN_DATA: CelestialBody = {
  id: 'sun',
  name: 'Sun (Sol)',
  type: 'star',
  radiusKm: 696340,
  massKg: 1.989e30,
  surfaceGravityMs2: 274.0,
  densityGcm3: 1.41,
  surfaceTemperatureK: 5778,
  geometricAlbedo: 1.0,
  rotationPeriodHours: 609.12, // ~25.38 Earth days at equator
  axialTiltDeg: 7.25,
  orbit: {
    semiMajorAxisAU: 0,
    eccentricity: 0,
    inclinationDeg: 0,
    orbitalPeriodDays: 0,
  },
  visualRadiusExploration: 3.2,
  visualRadiusScientific: 5.0,
  colorProfile: '#fff4cc',
  surfaceShaderId: 'sun',
  description: 'G2V yellow main-sequence star at the gravitational center of the Solar System, containing 99.86% of the system’s total mass.',
};

// ── 2. The Eight Planets & Major Moons ───────────────────────────────────────

export const PLANETS_DATA: CelestialBody[] = [
  // ── 1. MERCURY ──
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'planet',
    planetClass: 'terrestrial',
    parentId: 'sun',
    radiusKm: 2439.7,
    massKg: 3.3011e23,
    surfaceGravityMs2: 3.7,
    densityGcm3: 5.43,
    surfaceTemperatureK: 440,
    geometricAlbedo: 0.142,
    rotationPeriodHours: 1407.6, // 58.65 days (3:2 spin-orbit resonance)
    axialTiltDeg: 0.034,
    orbit: {
      semiMajorAxisAU: 0.387,
      eccentricity: 0.2056,
      inclinationDeg: 7.0,
      longitudeOfAscendingNodeDeg: 48.33,
      argumentOfPeriapsisDeg: 29.12,
      meanAnomalyAtEpochDeg: 174.79,
      orbitalPeriodDays: 87.97,
      orbitalVelocityKms: 47.36,
    },
    visualRadiusExploration: 0.55,
    visualRadiusScientific: 0.35,
    colorProfile: '#8c8680',
    surfaceShaderId: 'mercury',
    atmosphere: {
      hasAtmosphere: false,
      scaleHeightKm: 0,
      surfacePressureBar: 1e-14,
      scatteringColor: [0.1, 0.1, 0.1],
      opacity: 0,
      composition: 'Trace exosphere (Na, Mg, O, H, He)',
    },
    description: 'Innermost rocky planet with a cratered silicate crust, extreme day-night temperature swings, and a large metallic iron core.',
  },

  // ── 2. VENUS ──
  {
    id: 'venus',
    name: 'Venus',
    type: 'planet',
    planetClass: 'terrestrial',
    parentId: 'sun',
    radiusKm: 6051.8,
    massKg: 4.8675e24,
    surfaceGravityMs2: 8.87,
    densityGcm3: 5.24,
    surfaceTemperatureK: 737, // 464 °C runaway greenhouse
    geometricAlbedo: 0.689,
    rotationPeriodHours: -5832.5, // 243 days retrograde
    axialTiltDeg: 177.36,
    orbit: {
      semiMajorAxisAU: 0.723,
      eccentricity: 0.0067,
      inclinationDeg: 3.39,
      longitudeOfAscendingNodeDeg: 76.68,
      argumentOfPeriapsisDeg: 54.88,
      meanAnomalyAtEpochDeg: 50.11,
      orbitalPeriodDays: 224.7,
      orbitalVelocityKms: 35.02,
    },
    visualRadiusExploration: 0.85,
    visualRadiusScientific: 0.87,
    colorProfile: '#e6c88a',
    surfaceShaderId: 'venus',
    atmosphere: {
      hasAtmosphere: true,
      scaleHeightKm: 15.9,
      surfacePressureBar: 92.0,
      scatteringColor: [0.92, 0.82, 0.58],
      opacity: 0.95,
      composition: '96.5% CO₂, 3.5% N₂, Sulfuric acid clouds (H₂SO₄)',
      hasClouds: true,
      cloudSpeedFactor: -1.8,
    },
    description: 'Super-dense greenhouse world enveloped by opaque reflective sulfuric acid clouds with surface pressures 92 times that of Earth.',
  },

  // ── 3. EARTH & MOON ──
  {
    id: 'earth',
    name: 'Earth',
    type: 'planet',
    planetClass: 'terrestrial',
    parentId: 'sun',
    radiusKm: 6371.0,
    massKg: 5.9722e24,
    surfaceGravityMs2: 9.807,
    densityGcm3: 5.51,
    surfaceTemperatureK: 288,
    geometricAlbedo: 0.367,
    rotationPeriodHours: 23.934,
    axialTiltDeg: 23.44,
    orbit: {
      semiMajorAxisAU: 1.000,
      eccentricity: 0.0167,
      inclinationDeg: 0.00005,
      longitudeOfAscendingNodeDeg: -11.26,
      argumentOfPeriapsisDeg: 114.21,
      meanAnomalyAtEpochDeg: 358.62,
      orbitalPeriodDays: 365.256,
      orbitalVelocityKms: 29.78,
    },
    visualRadiusExploration: 0.92,
    visualRadiusScientific: 0.91,
    colorProfile: '#2b82c9',
    surfaceShaderId: 'earth',
    atmosphere: {
      hasAtmosphere: true,
      scaleHeightKm: 8.5,
      surfacePressureBar: 1.013,
      scatteringColor: [0.35, 0.65, 1.0],
      opacity: 0.85,
      composition: '78.08% N₂, 20.95% O₂, 0.93% Ar, 0.04% CO₂',
      hasClouds: true,
      cloudSpeedFactor: 1.15,
    },
    majorMoons: [
      {
        id: 'moon',
        name: 'Moon (Luna)',
        type: 'moon',
        parentId: 'earth',
        radiusKm: 1737.4,
        massKg: 7.342e22,
        surfaceGravityMs2: 1.62,
        densityGcm3: 3.34,
        surfaceTemperatureK: 220,
        rotationPeriodHours: 655.7,
        axialTiltDeg: 1.54,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00257, // 384,400 km
          eccentricity: 0.0549,
          inclinationDeg: 5.14,
          orbitalPeriodDays: 27.32,
        },
        visualRadiusExploration: 0.32,
        visualRadiusScientific: 0.25,
        colorProfile: '#999999',
        surfaceShaderId: 'moon',
        description: 'Earth’s large natural satellite, causing ocean tides and maintaining Earth’s stable axial obliquity.',
      },
    ],
    description: 'The only known habitable astronomical body, featuring liquid surface water oceans, plate tectonics, and a protective magnetosphere.',
  },

  // ── 4. MARS & MOONS ──
  {
    id: 'mars',
    name: 'Mars',
    type: 'planet',
    planetClass: 'terrestrial',
    parentId: 'sun',
    radiusKm: 3389.5,
    massKg: 6.4171e23,
    surfaceGravityMs2: 3.72,
    densityGcm3: 3.93,
    surfaceTemperatureK: 210,
    geometricAlbedo: 0.17,
    rotationPeriodHours: 24.623,
    axialTiltDeg: 25.19,
    orbit: {
      semiMajorAxisAU: 1.524,
      eccentricity: 0.0934,
      inclinationDeg: 1.85,
      longitudeOfAscendingNodeDeg: 49.56,
      argumentOfPeriapsisDeg: 286.50,
      meanAnomalyAtEpochDeg: 19.37,
      orbitalPeriodDays: 686.98,
      orbitalVelocityKms: 24.07,
    },
    visualRadiusExploration: 0.68,
    visualRadiusScientific: 0.49,
    colorProfile: '#c1440e',
    surfaceShaderId: 'mars',
    atmosphere: {
      hasAtmosphere: true,
      scaleHeightKm: 11.1,
      surfacePressureBar: 0.006,
      scatteringColor: [0.85, 0.55, 0.35],
      opacity: 0.40,
      composition: '95.3% CO₂, 2.6% N₂, 1.9% Ar',
    },
    majorMoons: [
      {
        id: 'phobos',
        name: 'Phobos',
        type: 'moon',
        parentId: 'mars',
        radiusKm: 11.2,
        massKg: 1.0659e16,
        surfaceGravityMs2: 0.0057,
        surfaceTemperatureK: 233,
        rotationPeriodHours: 7.66,
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.0000627, // 9,377 km
          eccentricity: 0.0151,
          inclinationDeg: 1.09,
          orbitalPeriodDays: 0.319,
        },
        visualRadiusExploration: 0.12,
        visualRadiusScientific: 0.06,
        colorProfile: '#595551',
        surfaceShaderId: 'rocky',
        description: 'Innermost, larger moon of Mars orbiting closer to its primary than any other moon in the Solar System.',
      },
      {
        id: 'deimos',
        name: 'Deimos',
        type: 'moon',
        parentId: 'mars',
        radiusKm: 6.2,
        massKg: 1.4762e15,
        surfaceGravityMs2: 0.003,
        surfaceTemperatureK: 233,
        rotationPeriodHours: 30.35,
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.0001568, // 23,460 km
          eccentricity: 0.0002,
          inclinationDeg: 1.79,
          orbitalPeriodDays: 1.263,
        },
        visualRadiusExploration: 0.09,
        visualRadiusScientific: 0.04,
        colorProfile: '#66615b',
        surfaceShaderId: 'rocky',
        description: 'Outer, smaller moon of Mars with a smooth regolith blanket covering impact craters.',
      },
    ],
    description: 'The Red Planet, characterized by iron-oxide dust, massive volcanoes (Olympus Mons), vast canyon systems (Valles Marineris), and polar water/CO₂ ice caps.',
  },

  // ── 5. JUPITER & GALILEAN MOONS ──
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'planet',
    planetClass: 'gas-giant',
    parentId: 'sun',
    radiusKm: 69911,
    massKg: 1.8982e27,
    surfaceGravityMs2: 24.79,
    densityGcm3: 1.33,
    surfaceTemperatureK: 165,
    geometricAlbedo: 0.538,
    rotationPeriodHours: 9.925, // Fastest planetary rotation in Solar System
    axialTiltDeg: 3.13,
    orbit: {
      semiMajorAxisAU: 5.204,
      eccentricity: 0.0484,
      inclinationDeg: 1.305,
      longitudeOfAscendingNodeDeg: 100.49,
      argumentOfPeriapsisDeg: 273.87,
      meanAnomalyAtEpochDeg: 20.02,
      orbitalPeriodDays: 4332.59,
      orbitalVelocityKms: 13.07,
    },
    visualRadiusExploration: 1.95,
    visualRadiusScientific: 2.20,
    colorProfile: '#c99039',
    surfaceShaderId: 'jupiter',
    atmosphere: {
      hasAtmosphere: true,
      scaleHeightKm: 27.0,
      surfacePressureBar: 2.0,
      scatteringColor: [0.88, 0.72, 0.50],
      opacity: 0.95,
      composition: '89.8% H₂, 10.2% He, trace CH₄, NH₃',
    },
    majorMoons: [
      {
        id: 'io',
        name: 'Io',
        type: 'moon',
        parentId: 'jupiter',
        radiusKm: 1821.6,
        massKg: 8.9319e22,
        surfaceGravityMs2: 1.796,
        surfaceTemperatureK: 130,
        rotationPeriodHours: 42.46,
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00282,
          eccentricity: 0.0041,
          inclinationDeg: 0.05,
          orbitalPeriodDays: 1.769,
        },
        visualRadiusExploration: 0.28,
        visualRadiusScientific: 0.26,
        colorProfile: '#d4a017',
        surfaceShaderId: 'io',
        description: 'Most volcanically active body in the Solar System, driven by tidal friction from Jupiter and orbital resonances with Europa and Ganymede.',
      },
      {
        id: 'europa',
        name: 'Europa',
        type: 'moon',
        parentId: 'jupiter',
        radiusKm: 1560.8,
        massKg: 4.7998e22,
        surfaceGravityMs2: 1.315,
        surfaceTemperatureK: 102,
        rotationPeriodHours: 85.23,
        axialTiltDeg: 0.1,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00448,
          eccentricity: 0.009,
          inclinationDeg: 0.47,
          orbitalPeriodDays: 3.551,
        },
        visualRadiusExploration: 0.25,
        visualRadiusScientific: 0.22,
        colorProfile: '#d8cfc4',
        surfaceShaderId: 'europa',
        description: 'Smooth icy crust covering a global liquid water ocean harboring more water than all of Earth’s oceans combined.',
      },
      {
        id: 'ganymede',
        name: 'Ganymede',
        type: 'moon',
        parentId: 'jupiter',
        radiusKm: 2634.1,
        massKg: 1.4819e23,
        surfaceGravityMs2: 1.428,
        surfaceTemperatureK: 110,
        rotationPeriodHours: 171.7,
        axialTiltDeg: 0.2,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00716,
          eccentricity: 0.0013,
          inclinationDeg: 0.20,
          orbitalPeriodDays: 7.155,
        },
        visualRadiusExploration: 0.36,
        visualRadiusScientific: 0.37,
        colorProfile: '#8c7d70',
        surfaceShaderId: 'rocky',
        description: 'Largest moon in the Solar System (larger than Mercury), and the only moon known to generate its own intrinsic magnetic field.',
      },
      {
        id: 'callisto',
        name: 'Callisto',
        type: 'moon',
        parentId: 'jupiter',
        radiusKm: 2410.3,
        massKg: 1.0759e23,
        surfaceGravityMs2: 1.235,
        surfaceTemperatureK: 134,
        rotationPeriodHours: 400.5,
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.01259,
          eccentricity: 0.0074,
          inclinationDeg: 0.28,
          orbitalPeriodDays: 16.689,
        },
        visualRadiusExploration: 0.33,
        visualRadiusScientific: 0.34,
        colorProfile: '#524b43',
        surfaceShaderId: 'rocky',
        description: 'Heavily cratered, geologically inactive ancient ice-rock moon with no orbital resonances.',
      },
    ],
    description: 'The giant of the Solar System, with alternating ammonia-cloud bands, hundreds of vortices, and the ancient Great Red Spot storm.',
  },

  // ── 6. SATURN & MOONS ──
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'planet',
    planetClass: 'gas-giant',
    parentId: 'sun',
    radiusKm: 58232,
    massKg: 5.6834e26,
    surfaceGravityMs2: 10.44,
    densityGcm3: 0.687, // Less dense than water
    surfaceTemperatureK: 134,
    geometricAlbedo: 0.499,
    rotationPeriodHours: 10.54,
    axialTiltDeg: 26.73,
    orbit: {
      semiMajorAxisAU: 9.582,
      eccentricity: 0.0555,
      inclinationDeg: 2.485,
      longitudeOfAscendingNodeDeg: 113.67,
      argumentOfPeriapsisDeg: 339.39,
      meanAnomalyAtEpochDeg: 317.02,
      orbitalPeriodDays: 10759.22,
      orbitalVelocityKms: 9.68,
    },
    visualRadiusExploration: 1.65,
    visualRadiusScientific: 1.85,
    colorProfile: '#e2bf7d',
    surfaceShaderId: 'saturn',
    atmosphere: {
      hasAtmosphere: true,
      scaleHeightKm: 59.5,
      surfacePressureBar: 1.4,
      scatteringColor: [0.89, 0.78, 0.58],
      opacity: 0.92,
      composition: '96.3% H₂, 3.25% He, trace CH₄, NH₃',
    },
    rings: {
      innerRadiusKm: 74500,  // C Ring inner edge
      outerRadiusKm: 140220, // A Ring outer edge
      color: [0.88, 0.80, 0.65],
      opacity: 0.88,
      textureType: 'saturn',
      hasGaps: true,
    },
    majorMoons: [
      {
        id: 'titan',
        name: 'Titan',
        type: 'moon',
        parentId: 'saturn',
        radiusKm: 2574.7,
        massKg: 1.3452e23,
        surfaceGravityMs2: 1.352,
        surfaceTemperatureK: 94,
        rotationPeriodHours: 382.7,
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00817,
          eccentricity: 0.0288,
          inclinationDeg: 0.35,
          orbitalPeriodDays: 15.945,
        },
        visualRadiusExploration: 0.35,
        visualRadiusScientific: 0.36,
        colorProfile: '#e59b2b',
        surfaceShaderId: 'titan',
        atmosphere: {
          hasAtmosphere: true,
          scaleHeightKm: 40.0,
          surfacePressureBar: 1.45,
          scatteringColor: [0.95, 0.65, 0.25],
          opacity: 0.95,
          composition: '95% N₂, 4.9% CH₄, hydrocarbon photochemical smog',
        },
        description: 'Only moon with a dense atmosphere and stable surface liquid bodies (methane/ethane lakes and seas).',
      },
      {
        id: 'enceladus',
        name: 'Enceladus',
        type: 'moon',
        parentId: 'saturn',
        radiusKm: 252.1,
        massKg: 1.08e20,
        surfaceGravityMs2: 0.113,
        surfaceTemperatureK: 75,
        rotationPeriodHours: 32.88,
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00159,
          eccentricity: 0.0047,
          inclinationDeg: 0.01,
          orbitalPeriodDays: 1.37,
        },
        visualRadiusExploration: 0.15,
        visualRadiusScientific: 0.08,
        colorProfile: '#ffffff',
        surfaceShaderId: 'europa',
        description: 'Bright icy moon with cryovolcanic geysers erupting water vapor and organic molecules from a subsurface ocean into Saturn’s E Ring.',
      },
      {
        id: 'rhea',
        name: 'Rhea',
        type: 'moon',
        parentId: 'saturn',
        radiusKm: 763.8,
        massKg: 2.306e21,
        surfaceGravityMs2: 0.264,
        surfaceTemperatureK: 73,
        rotationPeriodHours: 108.4,
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00352,
          eccentricity: 0.00125,
          inclinationDeg: 0.35,
          orbitalPeriodDays: 4.518,
        },
        visualRadiusExploration: 0.20,
        visualRadiusScientific: 0.14,
        colorProfile: '#b0a99f',
        surfaceShaderId: 'rocky',
        description: 'Second-largest moon of Saturn, heavily cratered and composed largely of water ice with a rocky core.',
      },
    ],
    description: 'Renowned for its magnificent, extensive ring system composed of billions of water ice particles and shepherd moons.',
  },

  // ── 7. URANUS & MOONS ──
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'planet',
    planetClass: 'ice-giant',
    parentId: 'sun',
    radiusKm: 25362,
    massKg: 8.681e25,
    surfaceGravityMs2: 8.87,
    densityGcm3: 1.27,
    surfaceTemperatureK: 76,
    geometricAlbedo: 0.488,
    rotationPeriodHours: -17.24, // Retrograde rotation
    axialTiltDeg: 97.77,        // Extreme tilt: orbits on its side
    orbit: {
      semiMajorAxisAU: 19.201,
      eccentricity: 0.0463,
      inclinationDeg: 0.773,
      longitudeOfAscendingNodeDeg: 74.01,
      argumentOfPeriapsisDeg: 96.99,
      meanAnomalyAtEpochDeg: 142.24,
      orbitalPeriodDays: 30685.4,
      orbitalVelocityKms: 6.80,
    },
    visualRadiusExploration: 1.20,
    visualRadiusScientific: 1.15,
    colorProfile: '#70d6db',
    surfaceShaderId: 'uranus',
    atmosphere: {
      hasAtmosphere: true,
      scaleHeightKm: 27.7,
      surfacePressureBar: 1.2,
      scatteringColor: [0.45, 0.85, 0.92],
      opacity: 0.88,
      composition: '83% H₂, 15% He, 2.3% CH₄ (methane absorption causes cyan color)',
    },
    rings: {
      innerRadiusKm: 38000,
      outerRadiusKm: 51149,
      color: [0.35, 0.45, 0.50],
      opacity: 0.35,
      textureType: 'uranus',
    },
    majorMoons: [
      {
        id: 'titania',
        name: 'Titania',
        type: 'moon',
        parentId: 'uranus',
        radiusKm: 788.4,
        massKg: 3.4e21,
        surfaceGravityMs2: 0.379,
        surfaceTemperatureK: 70,
        rotationPeriodHours: 208.9,
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00291,
          eccentricity: 0.0011,
          inclinationDeg: 0.34,
          orbitalPeriodDays: 8.706,
        },
        visualRadiusExploration: 0.18,
        visualRadiusScientific: 0.13,
        colorProfile: '#88827d',
        surfaceShaderId: 'rocky',
        description: 'Largest moon of Uranus, crisscrossed by massive fault canyons and grabens up to 1,500 km long.',
      },
      {
        id: 'oberon',
        name: 'Oberon',
        type: 'moon',
        parentId: 'uranus',
        radiusKm: 761.4,
        massKg: 3.01e21,
        surfaceGravityMs2: 0.346,
        surfaceTemperatureK: 70,
        rotationPeriodHours: 323.1,
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00390,
          eccentricity: 0.0014,
          inclinationDeg: 0.06,
          orbitalPeriodDays: 13.463,
        },
        visualRadiusExploration: 0.17,
        visualRadiusScientific: 0.12,
        colorProfile: '#7a746e',
        surfaceShaderId: 'rocky',
        description: 'Second-largest and outermost major Uranian moon, heavily cratered with mysterious dark deposits on crater floors.',
      },
    ],
    description: 'Cyan ice giant with a unique 97.8° axial obliquity, effectively rotating on its side and experiencing extreme 42-year polar seasons.',
  },

  // ── 8. NEPTUNE & TRITON ──
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'planet',
    planetClass: 'ice-giant',
    parentId: 'sun',
    radiusKm: 24622,
    massKg: 1.0243e26,
    surfaceGravityMs2: 11.15,
    densityGcm3: 1.638,
    surfaceTemperatureK: 72,
    geometricAlbedo: 0.442,
    rotationPeriodHours: 16.11,
    axialTiltDeg: 28.32,
    orbit: {
      semiMajorAxisAU: 30.047,
      eccentricity: 0.0095,
      inclinationDeg: 1.77,
      longitudeOfAscendingNodeDeg: 131.78,
      argumentOfPeriapsisDeg: 273.19,
      meanAnomalyAtEpochDeg: 256.23,
      orbitalPeriodDays: 60189.0,
      orbitalVelocityKms: 5.43,
    },
    visualRadiusExploration: 1.18,
    visualRadiusScientific: 1.12,
    colorProfile: '#274687',
    surfaceShaderId: 'neptune',
    atmosphere: {
      hasAtmosphere: true,
      scaleHeightKm: 19.7,
      surfacePressureBar: 1.3,
      scatteringColor: [0.20, 0.45, 0.95],
      opacity: 0.92,
      composition: '80% H₂, 19% He, 1.5% CH₄',
    },
    majorMoons: [
      {
        id: 'triton',
        name: 'Triton',
        type: 'moon',
        parentId: 'neptune',
        radiusKm: 1353.4,
        massKg: 2.14e22,
        surfaceGravityMs2: 0.779,
        surfaceTemperatureK: 38, // Coldest measured body in Solar System
        rotationPeriodHours: -141.0, // Retrograde orbit
        axialTiltDeg: 0,
        isTidallyLocked: true,
        orbit: {
          semiMajorAxisAU: 0.00237,
          eccentricity: 0.000016,
          inclinationDeg: 156.885, // Retrograde capture
          orbitalPeriodDays: 5.877,
        },
        visualRadiusExploration: 0.24,
        visualRadiusScientific: 0.20,
        colorProfile: '#b5c4bf',
        surfaceShaderId: 'europa',
        description: 'Captured Kuiper Belt dwarf planet with active nitrogen geysers and a cantaloupe terrain surface.',
      },
    ],
    description: 'Outermost major planet, featuring the fastest supersonic winds in the Solar System (up to 2,100 km/h) and active methane cirrus clouds.',
  },
];

// ── 3. Major Dwarf Planets ───────────────────────────────────────────────────

export const DWARF_PLANETS_DATA: CelestialBody[] = [
  {
    id: 'ceres',
    name: 'Ceres',
    type: 'dwarf-planet',
    parentId: 'sun',
    radiusKm: 473.0,
    massKg: 9.3835e20,
    surfaceGravityMs2: 0.28,
    surfaceTemperatureK: 168,
    rotationPeriodHours: 9.07,
    axialTiltDeg: 4.0,
    orbit: {
      semiMajorAxisAU: 2.767,
      eccentricity: 0.0758,
      inclinationDeg: 10.59,
      orbitalPeriodDays: 1681.63,
    },
    visualRadiusExploration: 0.22,
    visualRadiusScientific: 0.12,
    colorProfile: '#6f6c68',
    surfaceShaderId: 'rocky',
    description: 'Largest object in the asteroid belt, containing roughly one-third of the belt’s total mass, featuring bright sodium carbonate deposits.',
    discoveryYear: 1801,
  },
  {
    id: 'pluto',
    name: 'Pluto',
    type: 'dwarf-planet',
    parentId: 'sun',
    radiusKm: 1188.3,
    massKg: 1.303e22,
    surfaceGravityMs2: 0.62,
    surfaceTemperatureK: 44,
    rotationPeriodHours: -153.3, // 6.387 days retrograde
    axialTiltDeg: 122.53,
    orbit: {
      semiMajorAxisAU: 39.482,
      eccentricity: 0.2488,
      inclinationDeg: 17.16,
      orbitalPeriodDays: 90560.0,
    },
    visualRadiusExploration: 0.28,
    visualRadiusScientific: 0.18,
    colorProfile: '#c49e7a',
    surfaceShaderId: 'rocky',
    description: 'Prominent Kuiper Belt dwarf planet featuring the nitrogen-ice glacier plain Sputnik Planitia and a 3:2 orbital resonance with Neptune.',
    discoveryYear: 1930,
  },
  {
    id: 'haumea',
    name: 'Haumea',
    type: 'dwarf-planet',
    parentId: 'sun',
    radiusKm: 780.0, // Highly elongated ellipsoid (approx radius)
    massKg: 4.006e21,
    surfaceGravityMs2: 0.40,
    surfaceTemperatureK: 50,
    rotationPeriodHours: 3.915, // Extremely fast rotation
    axialTiltDeg: 28.0,
    orbit: {
      semiMajorAxisAU: 43.218,
      eccentricity: 0.1912,
      inclinationDeg: 28.19,
      orbitalPeriodDays: 103774.0,
    },
    visualRadiusExploration: 0.24,
    visualRadiusScientific: 0.14,
    colorProfile: '#c8cbd1',
    surfaceShaderId: 'rocky',
    description: 'Rapidly spinning triaxial ellipsoid trans-Neptunian object with a crystalline water ice surface and a faint ring system.',
    discoveryYear: 2004,
  },
  {
    id: 'makemake',
    name: 'Makemake',
    type: 'dwarf-planet',
    parentId: 'sun',
    radiusKm: 715.0,
    massKg: 3.1e21,
    surfaceGravityMs2: 0.45,
    surfaceTemperatureK: 35,
    rotationPeriodHours: 22.83,
    axialTiltDeg: 29.0,
    orbit: {
      semiMajorAxisAU: 45.715,
      eccentricity: 0.1559,
      inclinationDeg: 28.96,
      orbitalPeriodDays: 112897.0,
    },
    visualRadiusExploration: 0.23,
    visualRadiusScientific: 0.13,
    colorProfile: '#b8724d',
    surfaceShaderId: 'rocky',
    description: 'Bright Kuiper Belt dwarf planet covered in frozen methane and tholins with no detected significant atmosphere.',
    discoveryYear: 2005,
  },
  {
    id: 'eris',
    name: 'Eris',
    type: 'dwarf-planet',
    parentId: 'sun',
    radiusKm: 1163.0,
    massKg: 1.66e22,
    surfaceGravityMs2: 0.82,
    surfaceTemperatureK: 32,
    rotationPeriodHours: 25.9,
    axialTiltDeg: 44.0,
    orbit: {
      semiMajorAxisAU: 67.781,
      eccentricity: 0.4407,
      inclinationDeg: 44.04,
      orbitalPeriodDays: 203830.0,
    },
    visualRadiusExploration: 0.27,
    visualRadiusScientific: 0.17,
    colorProfile: '#dedede',
    surfaceShaderId: 'rocky',
    description: 'Most massive known dwarf planet, located in the scattered disc with a highly inclined and eccentric 558-year orbit.',
    discoveryYear: 2005,
  },
];

// ── 4. Small Body Populations Config ─────────────────────────────────────────

export const ASTEROID_BELT_CONFIG: AsteroidBeltConfig = {
  innerRadiusAU: 2.1,
  outerRadiusAU: 3.3,
  count: 6000,
  meanInclinationDeg: 9.5,
  thicknessAU: 0.45,
};

export const KUIPER_BELT_CONFIG: KuiperBeltConfig = {
  innerRadiusAU: 30.0,
  outerRadiusAU: 52.0,
  count: 8000,
  meanInclinationDeg: 14.0,
  thicknessAU: 1.8,
};

// ── 5. Representative Comets ─────────────────────────────────────────────────

export const COMETS_DATA: CometTrajectory[] = [
  {
    id: '1p-halley',
    name: '1P/Halley',
    semiMajorAxisAU: 17.83,
    eccentricity: 0.967,
    inclinationDeg: 162.3, // Retrograde
    periodYears: 75.3,
    perihelionAU: 0.586,
    aphelionAU: 35.1,
    nucleusRadiusKm: 5.5,
    tailColor: [0.4, 0.75, 1.0],
  },
  {
    id: '2p-encke',
    name: '2P/Encke',
    semiMajorAxisAU: 2.21,
    eccentricity: 0.848,
    inclinationDeg: 11.78,
    periodYears: 3.30,
    perihelionAU: 0.336,
    aphelionAU: 4.09,
    nucleusRadiusKm: 2.4,
    tailColor: [0.6, 0.85, 0.9],
  },
  {
    id: 'hale-bopp',
    name: 'C/1995 O1 (Hale-Bopp)',
    semiMajorAxisAU: 186.0,
    eccentricity: 0.995,
    inclinationDeg: 89.4,
    periodYears: 2537.0,
    perihelionAU: 0.914,
    aphelionAU: 371.0,
    nucleusRadiusKm: 30.0,
    tailColor: [0.35, 0.80, 1.0],
  },
];
