/**
 * EducationContent.ts
 * Comprehensive database of educational astrophysical concepts.
 * Contains 28 rich concept definitions with equations, variables, importance,
 * related topic IDs, tags, and model simplification annotations.
 */

import type { EducationalConcept } from './EducationTypes';

export const EDUCATIONAL_CONCEPTS: EducationalConcept[] = [
  {
    id: 'stellar-fusion',
    title: 'Nuclear Fusion in Stars',
    category: 'FUSION',
    shortExplanation: 'The thermonuclear synthesis of heavier atomic nuclei from lighter ones, releasing tremendous binding energy.',
    detailedExplanation: 'Under extreme core temperatures (T > 10⁷ K) and densities, hydrogen nuclei overcome their electrostatic Coulomb barrier through quantum mechanical tunneling. In stars with M ≲ 1.3 M☉, the Proton-Proton (p-p) chain dominates. In more massive stars, the carbon-nitrogen-oxygen (CNO) catalytic cycle powers the core.',
    keyEquation: {
      title: 'Mass-Energy Equivalence',
      text: 'ΔE = Δm · c²',
      variables: [
        { symbol: 'ΔE', name: 'Released Energy', unit: 'Joules (J)', description: 'Binding energy released by mass deficit.' },
        { symbol: 'Δm', name: 'Mass Deficit', unit: 'kg', description: 'Difference between reactants and product mass (0.7% for 4H → ⁴He).' },
        { symbol: 'c', name: 'Speed of Light', unit: 'm/s', description: '299,792,458 m/s.' },
      ],
      notes: 'Approximately 0.71% of rest hydrogen mass is converted into radiant energy during helium synthesis.',
    },
    importance: 'Nuclear fusion is the primary energy source combating gravitational collapse and synthesizing all chemical elements beyond hydrogen and helium.',
    relatedTopicIds: ['hydrostatic-equilibrium', 'main-sequence', 'cno-cycle', 'triple-alpha'],
    tags: ['Fusion', 'p-p chain', 'CNO', 'Thermonuclear', 'Binding Energy'],
  },
  {
    id: 'cno-cycle',
    title: 'Carbon-Nitrogen-Oxygen (CNO) Cycle',
    category: 'FUSION',
    shortExplanation: 'A catalytic thermonuclear fusion cycle dominant in stars with mass M > 1.3 M☉.',
    detailedExplanation: 'Carbon, nitrogen, and oxygen nuclei act as catalysts to fuse four protons into a helium-4 nucleus. Because of the higher Coulomb barrier of carbon, the CNO cycle has a steep temperature sensitivity (ε ∝ T¹⁶ - T¹⁸), creating convective cores in massive stars.',
    importance: 'The dominant energy generation mechanism in intermediate, massive, and supergiant stars.',
    relatedTopicIds: ['stellar-fusion', 'main-sequence', 'triple-alpha'],
    tags: ['CNO', 'Fusion', 'Massive Stars', 'Catalysis'],
  },
  {
    id: 'hydrostatic-equilibrium',
    title: 'Hydrostatic Equilibrium',
    category: 'STELLAR_STRUCTURE',
    shortExplanation: 'The exact balance between the inward pull of gravity and the outward push of thermal gas and radiation pressure.',
    detailedExplanation: 'Every spherical shell of a star in hydrostatic balance experiences an inward gravitational force balanced precisely by the radial gradient of internal pressure. If core energy generation decreases, the star contracts until core density and temperature rise sufficiently to restore equilibrium.',
    keyEquation: {
      title: 'Hydrostatic Equilibrium Gradient',
      text: 'dP/dr = - G · M(r) · ρ(r) / r²',
      variables: [
        { symbol: 'dP/dr', name: 'Pressure Gradient', unit: 'Pa/m', description: 'Radial change in outward pressure.' },
        { symbol: 'G', name: 'Gravitational Constant', unit: 'm³/(kg·s²)', description: '6.6743 × 10⁻¹¹ m³/(kg·s²).' },
        { symbol: 'M(r)', name: 'Enclosed Mass', unit: 'kg', description: 'Total stellar mass interior to radius r.' },
        { symbol: 'ρ(r)', name: 'Local Density', unit: 'kg/m³', description: 'Mass density of gas at radius r.' },
      ],
    },
    importance: 'Maintains the stable structural radius of main sequence stars and giants for millions to trillions of years.',
    relatedTopicIds: ['stellar-fusion', 'kelvin-helmholtz', 'core-collapse'],
    tags: ['Equilibrium', 'Gravity', 'Pressure Gradient', 'Stellar Structure'],
  },
  {
    id: 'stefan-boltzmann',
    title: 'Stefan-Boltzmann Law & Blackbody Radiation',
    category: 'STELLAR_STRUCTURE',
    shortExplanation: 'Relates total radiated power (luminosity) of a star to its surface area and fourth power of effective temperature.',
    detailedExplanation: 'Stars radiate approximately as ideal blackbodies. The Stefan-Boltzmann law dictates that luminosity scales with the square of radius and fourth power of temperature. Even a modest increase in surface temperature produces a dramatic surge in emitted radiant flux.',
    keyEquation: {
      title: 'Stefan-Boltzmann Radiation Law',
      text: 'L = 4π · R² · σ · T_eff⁴',
      variables: [
        { symbol: 'L', name: 'Luminosity', unit: 'Watts (W)', description: 'Total bolometric energy emitted per second.' },
        { symbol: 'R', name: 'Photosphere Radius', unit: 'meters (m)', description: 'Radius of the optical surface.' },
        { symbol: 'σ', name: 'Stefan-Boltzmann Constant', unit: 'W/(m²·K⁴)', description: '5.6704 × 10⁻⁸ W/(m²·K⁴).' },
        { symbol: 'T_eff', name: 'Effective Temperature', unit: 'Kelvin (K)', description: 'Blackbody equivalent surface temperature.' },
      ],
    },
    importance: 'Fundamental anchor allowing astronomers to deduce stellar radii from measured luminosity and spectral temperature.',
    relatedTopicIds: ['hr-diagram', 'spectral-classification', 'main-sequence'],
    tags: ['Radiation', 'Blackbody', 'Luminosity', 'Temperature'],
  },
  {
    id: 'mass-luminosity',
    title: 'Mass-Luminosity Relation',
    category: 'STELLAR_STRUCTURE',
    shortExplanation: 'Empirical and theoretical power law demonstrating that stellar luminosity scales steeply with initial mass (L ∝ M^α).',
    detailedExplanation: 'For main sequence stars, central core pressure and radiative transport require a steep increase in luminosity with mass (typically α ≈ 3.5 for solar-type stars). Consequently, a star 10 times more massive than the Sun radiates roughly 3,000 times more energy and burns through its fuel 300 times faster.',
    keyEquation: {
      title: 'Mass-Luminosity Scaling',
      text: 'L / L☉ ≈ (M / M☉)^α  (α ≈ 3.5 - 4.0)',
      variables: [
        { symbol: 'L/L☉', name: 'Luminosity in Solar Units', unit: 'dimensionless', description: 'Normalized stellar power.' },
        { symbol: 'M/M☉', name: 'Mass in Solar Units', unit: 'dimensionless', description: 'Normalized stellar mass.' },
        { symbol: 'α', name: 'Power-Law Index', unit: 'dimensionless', description: 'Ranges from 2.3 for low mass to 3.8 for solar, softening at Eddington limit.' },
      ],
    },
    importance: 'Explains why massive O/B stars have short million-year lifetimes while low-mass M dwarfs burn for trillions of years.',
    relatedTopicIds: ['main-sequence', 'stellar-fusion', 'eddington-limit'],
    tags: ['Mass-Luminosity', 'Stellar Lifetime', 'Power Law'],
  },
  {
    id: 'eddington-limit',
    title: 'Eddington Luminosity Limit',
    category: 'STELLAR_STRUCTURE',
    shortExplanation: 'The maximum theoretical luminosity a star in hydrostatic balance can achieve before radiation pressure blows away its outer layers.',
    detailedExplanation: 'When photon radiation pressure acting on free electrons via Thomson scattering equals the inward gravitational attraction on surrounding ions, hydrostatic equilibrium breaks down. Stars approaching this limit experience violent line-driven stellar winds and mass ejections.',
    keyEquation: {
      title: 'Eddington Luminosity',
      text: 'L_Edd = 4π · G · M · c / κ',
      variables: [
        { symbol: 'L_Edd', name: 'Eddington Luminosity', unit: 'Watts (W)', description: 'Maximum stable radiation power.' },
        { symbol: 'G', name: 'Gravitational Constant', unit: 'm³/(kg·s²)', description: '6.6743 × 10⁻¹¹.' },
        { symbol: 'M', name: 'Stellar Mass', unit: 'kg', description: 'Total mass of the object.' },
        { symbol: 'c', name: 'Speed of Light', unit: 'm/s', description: '299,792,458 m/s.' },
        { symbol: 'κ', name: 'Electron Opacity', unit: 'm²/kg', description: 'Thomson electron scattering cross-section per unit mass.' },
      ],
    },
    importance: 'Sets the physical upper limit on stable stellar masses (~150 - 300 M☉) and governs accretion limits onto black holes.',
    relatedTopicIds: ['mass-luminosity', 'black-hole', 'stellar-mass-loss'],
    tags: ['Eddington Limit', 'Radiation Pressure', 'Mass Loss'],
  },
  {
    id: 'stellar-mass-loss',
    title: 'Stellar Winds & Mass Loss (Reimers & de Jager)',
    category: 'EVOLUTION',
    shortExplanation: 'The ejection of outer envelope gas via radiation pressure, stellar winds, and pulsating superwinds.',
    detailedExplanation: 'As stars evolve into red giants and supergiants, low surface gravity and high opacity drive massive mass-loss rates via Reimers’ formula (for AGB giants) and de Jager scaling (for massive supergiants), shedding up to 80% of their initial envelope mass.',
    importance: 'Governs remnant core masses and enriches the interstellar medium with synthesized metals.',
    relatedTopicIds: ['asymptotic-giant-branch', 'planetary-nebula', 'eddington-limit'],
    tags: ['Mass Loss', 'Stellar Winds', 'Reimers', 'de Jager'],
  },
  {
    id: 'jeans-instability',
    title: 'Jeans Instability & Cloud Collapse',
    category: 'GRAVITY',
    shortExplanation: 'The physical criterion determining whether a cold interstellar gas cloud has sufficient mass to overcome internal thermal gas pressure and collapse into protostars.',
    detailedExplanation: 'Sir James Jeans demonstrated that small density perturbations in an isothermal gas become gravitationally unstable if self-gravity exceeds thermal pressure. If a cloud mass exceeds the Jeans Mass (M_J), collapse is inevitable, leading to fragmentation and cluster formation.',
    keyEquation: {
      title: 'Jeans Mass',
      text: 'M_J = (π/6) · ρ · λ_J³ = (π/6) · c_s³ / (G^(3/2) · ρ^(1/2))',
      variables: [
        { symbol: 'M_J', name: 'Jeans Mass', unit: 'kg', description: 'Minimum mass required for gravitational collapse.' },
        { symbol: 'c_s', name: 'Sound Speed', unit: 'm/s', description: 'Isothermal sound speed in cold gas (c_s = √(k_B T / μ m_H)).' },
        { symbol: 'ρ', name: 'Gas Density', unit: 'kg/m³', description: 'Mass density of the molecular cloud.' },
        { symbol: 'G', name: 'Gravitational Constant', unit: 'm³/(kg·s²)', description: '6.6743 × 10⁻¹¹.' },
      ],
    },
    importance: 'Governs the initial trigger for all star and star-cluster formation in galaxies.',
    relatedTopicIds: ['free-fall-time', 'protostar', 'kelvin-helmholtz'],
    tags: ['Star Birth', 'Jeans Mass', 'Cloud Collapse', 'Molecular Cloud'],
  },
  {
    id: 'free-fall-time',
    title: 'Free-Fall Gravitational Collapse Timescale',
    category: 'GRAVITY',
    shortExplanation: 'The characteristic time it would take a pressureless sphere of uniform density to collapse to a central point under its own gravity.',
    detailedExplanation: 'The free-fall timescale depends solely on the initial mass density of the gas cloud, independent of the cloud’s total radius. Denser cores collapse much faster than surrounding diffuse envelopes, driving rapid hierarchical fragmentation.',
    keyEquation: {
      title: 'Free-Fall Timescale',
      text: 't_ff = √(3π / (32 · G · ρ))',
      variables: [
        { symbol: 't_ff', name: 'Free-Fall Time', unit: 'seconds (s)', description: 'Characteristic collapse duration.' },
        { symbol: 'G', name: 'Gravitational Constant', unit: 'm³/(kg·s²)', description: '6.6743 × 10⁻¹¹.' },
        { symbol: 'ρ', name: 'Cloud Density', unit: 'kg/m³', description: 'Mean mass density of collapsing cloud.' },
      ],
    },
    importance: 'Establishes the fundamental dynamical clock for molecular cloud collapse and protostellar core accretion.',
    relatedTopicIds: ['jeans-instability', 'protostar', 'core-collapse'],
    tags: ['Timescale', 'Free Fall', 'Dynamics', 'Star Birth'],
  },
  {
    id: 'protostar',
    title: 'Protostellar Core & Accretion',
    category: 'EVOLUTION',
    shortExplanation: 'An early stage of stellar formation where an infalling gas envelope feeds a contracting central core before thermonuclear ignition.',
    detailedExplanation: 'Gas from the molecular cloud accretes onto the central core via a circumstellar accretion disk. Infalling gravitational potential energy is converted to thermal radiation and bipolar magnetocentrifugal jets until the star contracts to the Zero-Age Main Sequence.',
    importance: 'The foundational gestation phase that sets final stellar mass and builds planetary systems.',
    relatedTopicIds: ['jeans-instability', 'kelvin-helmholtz', 'main-sequence'],
    tags: ['Protostar', 'Accretion', 'Star Birth'],
  },
  {
    id: 'kelvin-helmholtz',
    title: 'Kelvin-Helmholtz Contraction',
    category: 'EVOLUTION',
    shortExplanation: 'The gravitational timescale over which a contracting protostar radiates its gravitational potential energy before nuclear fusion ignites.',
    detailedExplanation: 'According to the Virial Theorem, half of the gravitational potential energy released during contraction is radiated away as surface luminosity, while the other half heats the interior. This contraction continues until the central core reaches ~10⁷ K, triggering hydrogen fusion.',
    keyEquation: {
      title: 'Kelvin-Helmholtz Timescale',
      text: 't_KH = G · M² / (R · L)',
      variables: [
        { symbol: 't_KH', name: 'KH Timescale', unit: 'years / seconds', description: 'Thermal timescale of star (~30 Myr for the Sun).' },
        { symbol: 'M', name: 'Stellar Mass', unit: 'kg', description: 'Total mass of contracting star.' },
        { symbol: 'R', name: 'Stellar Radius', unit: 'm', description: 'Mean radius of star.' },
        { symbol: 'L', name: 'Luminosity', unit: 'W', description: 'Radiant energy emitted per second.' },
      ],
    },
    importance: 'Explains protostellar pre-main-sequence evolution and the source of energy in giant gas planets and pre-ignition cores.',
    relatedTopicIds: ['protostar', 'hydrostatic-equilibrium', 'main-sequence'],
    tags: ['Contraction', 'Virial Theorem', 'Pre-Main Sequence', 'Timescale'],
  },
  {
    id: 'main-sequence',
    title: 'Main Sequence (Hydrogen Burning)',
    category: 'EVOLUTION',
    shortExplanation: 'The longest, most stable phase of a star’s lifetime, characterized by core hydrogen fusion into helium in hydrostatic equilibrium.',
    detailedExplanation: 'Stars spend ~90% of their total active lifespans on the Main Sequence. Over this period, core hydrogen fraction X decreases while core helium fraction Y increases. As mean molecular weight rises, core temperature increases slightly, causing the star to slowly brighten and expand over billions of years.',
    importance: 'The foundational stellar phase that hosts habitable zones and stabilizes planetary systems.',
    relatedTopicIds: ['stellar-fusion', 'hr-diagram', 'mass-luminosity', 'red-giant'],
    tags: ['Main Sequence', 'ZAMS', 'Hydrogen Core', 'Stellar Lifetime'],
  },
  {
    id: 'red-giant',
    title: 'Red Giant & Supergiant Expansion',
    category: 'EVOLUTION',
    shortExplanation: 'The dramatic expansion and surface cooling of a star following core hydrogen exhaustion and hydrogen shell ignition.',
    detailedExplanation: 'When core hydrogen is depleted, the inert helium core contracts and heats under gravity. The surrounding hydrogen-rich shell heats up, igniting furious shell fusion. The tremendous energy flux forces the outer envelope to expand outward by factors of 100 to 1,000, cooling the surface into an luminous red giant or supergiant.',
    importance: 'Drives massive stellar wind enrichment and will engulf the inner planets of our Solar System in ~5 billion years.',
    relatedTopicIds: ['main-sequence', 'triple-alpha', 'asymptotic-giant-branch', 'planetary-nebula'],
    tags: ['Red Giant', 'Supergiant', 'Shell Burning', 'Hayashi Track'],
  },
  {
    id: 'helium-flash',
    title: 'The Helium Flash',
    category: 'FUSION',
    shortExplanation: 'Runaway thermonuclear ignition of helium in the degenerate core of low-mass red giant stars.',
    detailedExplanation: 'In stars with mass M ≲ 2.0 M☉, the contracted helium core becomes electron-degenerate before reaching 10⁸ K. Degenerate pressure is independent of temperature; thus, when helium ignites, the core cannot expand to cool itself, causing a runaway thermonuclear flash releasing ~10¹¹ L☉ internally until thermal pressure lifts degeneracy.',
    importance: 'Marks the rapid transition of low-mass stars from the Red Giant tip onto the stable Horizontal Branch.',
    relatedTopicIds: ['red-giant', 'triple-alpha', 'electron-degeneracy'],
    tags: ['Helium Flash', 'Degeneracy', 'Thermal Runaway'],
  },
  {
    id: 'triple-alpha',
    title: 'Triple-Alpha Helium Fusion',
    category: 'FUSION',
    shortExplanation: 'Thermonuclear process converting three helium-4 nuclei (alpha particles) into stable carbon-12 and oxygen-16.',
    detailedExplanation: 'Because two helium-4 nuclei form unstable beryllium-8 with a half-life of 10⁻¹⁶ seconds, a third alpha particle must collide almost instantaneously to produce carbon-12. This requires extreme temperatures (T ≳ 10⁸ K) and exhibits an astronomical temperature sensitivity (energy generation rate ε ∝ T⁴⁰).',
    keyEquation: {
      title: 'Triple-Alpha Reaction Steps',
      text: '⁴He + ⁴He ⇌ ⁸Be,   ⁸Be + ⁴He → ¹²C* → ¹²C + γ (7.27 MeV)',
      variables: [
        { symbol: '⁴He', name: 'Alpha Particle (Helium-4 nucleus)', unit: 'amu', description: 'Stable helium nucleus.' },
        { symbol: '¹²C', name: 'Carbon-12', unit: 'amu', description: 'Product of triple-alpha fusion.' },
        { symbol: 'γ', name: 'Gamma Photon', unit: 'MeV', description: 'Binding energy released.' },
      ],
    },
    importance: 'The primary cosmological origin of carbon, oxygen, and heavier elements essential for organic life.',
    relatedTopicIds: ['red-giant', 'helium-flash', 'asymptotic-giant-branch'],
    tags: ['Helium Burning', 'Carbon-12', 'Triple Alpha', 'Nucleosynthesis'],
  },
  {
    id: 'asymptotic-giant-branch',
    title: 'Asymptotic Giant Branch (AGB)',
    category: 'EVOLUTION',
    shortExplanation: 'Late evolutionary phase of low/intermediate mass stars characterized by double shell burning around a degenerate C/O core.',
    detailedExplanation: 'Following core helium exhaustion, stars develop an inner helium-burning shell and outer hydrogen-burning shell surrounding an inert degenerate carbon-oxygen core. Periodic thermal pulses generate deep convective dredge-up episodes and intense superwinds.',
    importance: 'Synthesizes roughly half of all elements heavier than iron via slow neutron capture (s-process).',
    relatedTopicIds: ['red-giant', 'triple-alpha', 'planetary-nebula', 'white-dwarf'],
    tags: ['AGB', 'Double Shell Burning', 'Thermal Pulses', 's-process'],
  },
  {
    id: 'electron-degeneracy',
    title: 'Electron Degeneracy Pressure',
    category: 'REMNANTS',
    shortExplanation: 'Quantum mechanical pressure arising from the Pauli Exclusion Principle preventing identical fermions from occupying the same quantum state.',
    detailedExplanation: 'When matter is compressed to extreme densities (ρ ~ 10⁹ kg/m³), electrons are forced into tightly packed phase-space cells. By the Pauli Exclusion Principle, electrons occupy distinct high-momentum quantum states regardless of temperature. This non-thermal pressure supports White Dwarfs against gravitational collapse.',
    keyEquation: {
      title: 'Non-Relativistic Degeneracy Pressure',
      text: 'P_deg = K_1 · (ρ / μ_e)^(5/3)',
      variables: [
        { symbol: 'P_deg', name: 'Degeneracy Pressure', unit: 'Pa', description: 'Non-thermal quantum pressure independent of T.' },
        { symbol: 'ρ', name: 'Mass Density', unit: 'kg/m³', description: 'Core density.' },
        { symbol: 'μ_e', name: 'Mean Molecular Weight per Electron', unit: 'dimensionless', description: '≈ 2 for carbon-oxygen.' },
      ],
      notes: 'Under extreme relativistic speeds, pressure softens to P ∝ ρ^(4/3), leading directly to the Chandrasekhar Limit.',
    },
    importance: 'Explains why White Dwarfs do not collapse into black holes despite having zero ongoing nuclear fusion.',
    relatedTopicIds: ['chandrasekhar-limit', 'white-dwarf', 'neutron-degeneracy'],
    tags: ['Quantum Mechanics', 'Pauli Exclusion', 'Degeneracy', 'White Dwarf'],
  },
  {
    id: 'neutron-degeneracy',
    title: 'Neutron Degeneracy Pressure',
    category: 'REMNANTS',
    shortExplanation: 'Quantum mechanical pressure from tightly packed degenerate neutrons supporting neutron stars against collapse.',
    detailedExplanation: 'At densities exceeding 10¹⁷ kg/m³, electron degeneracy fails and inverse beta decay converts protons and electrons into neutrons. Degenerate neutrons combined with repulsive nuclear strong forces support the star up to the TOV limit.',
    importance: 'The ultimate material pressure barrier before complete general relativistic collapse into a black hole.',
    relatedTopicIds: ['neutron-star', 'tov-limit', 'electron-degeneracy'],
    tags: ['Neutron Degeneracy', 'Nuclear Force', 'Quantum Physics'],
  },
  {
    id: 'chandrasekhar-limit',
    title: 'The Chandrasekhar Mass Limit (≈ 1.44 M☉)',
    category: 'REMNANTS',
    shortExplanation: 'The maximum theoretical mass that an electron-degenerate white dwarf can support against its own gravity.',
    detailedExplanation: 'Derived by Subrahmanyan Chandrasekhar in 1930. As a white dwarf’s mass increases, electrons become ultra-relativistic. The equation of state softens from P ∝ ρ^(5/3) to P ∝ ρ^(4/3). At M_Ch ≈ 1.44 M☉, electron degeneracy pressure can no longer balance gravity, causing catastrophic collapse.',
    keyEquation: {
      title: 'Chandrasekhar Mass Formula',
      text: 'M_Ch = (ω_3^0 / 4π) · (hc / G)^(3/2) · (1 / (μ_e · m_H)²) ≈ 1.44 M☉',
      variables: [
        { symbol: 'M_Ch', name: 'Chandrasekhar Limit', unit: 'M☉', description: '≈ 1.44 Solar Masses.' },
        { symbol: 'h', name: 'Planck Constant', unit: 'J·s', description: '6.626 × 10⁻³⁴ J·s.' },
        { symbol: 'c', name: 'Speed of Light', unit: 'm/s', description: '299,792,458 m/s.' },
        { symbol: 'G', name: 'Gravitational Constant', unit: 'm³/(kg·s²)', description: '6.6743 × 10⁻¹¹.' },
        { symbol: 'μ_e', name: 'Electrons per Nucleon', unit: 'dimensionless', description: '≈ 2.0 for C/O.' },
      ],
    },
    importance: 'The fundamental threshold dividing gentle planetary nebula white-dwarf fates from catastrophic supernova core-collapses.',
    relatedTopicIds: ['electron-degeneracy', 'white-dwarf', 'core-collapse'],
    tags: ['Chandrasekhar Limit', 'White Dwarf Limit', 'Relativistic Quantum Mechanics'],
  },
  {
    id: 'white-dwarf',
    title: 'White Dwarf & Mestel Cooling Law',
    category: 'REMNANTS',
    shortExplanation: 'A stellar remnant composed of electron-degenerate matter that slowly radiates away its residual thermal heat over trillions of years.',
    detailedExplanation: 'White dwarfs pack roughly the mass of the Sun into a volume comparable to Earth (R ≈ 0.01 R☉). Because electron degeneracy supports the structure, the star has an inverted mass-radius relation: more massive white dwarfs are physically smaller. Over cosmological timescales, they cool via the Mestel cooling law (L ∝ t^(-7/6)).',
    importance: 'The final retirement graveyard for over 97% of all stars in the Milky Way galaxy.',
    relatedTopicIds: ['electron-degeneracy', 'chandrasekhar-limit', 'planetary-nebula'],
    tags: ['White Dwarf', 'Remnant', 'Degeneracy', 'Mestel Cooling'],
  },
  {
    id: 'planetary-nebula',
    title: 'Planetary Nebula',
    category: 'REMNANTS',
    shortExplanation: 'An expanding glowing shell of ionized gas ejected by an Asymptotic Giant Branch star at the end of its life.',
    detailedExplanation: 'During late AGB thermal pulses, radiation pressure detaches the star’s loose outer envelope, propelling it into interstellar space at 20 - 30 km/s. The newly exposed ultra-hot core (T > 100,000 K) emits intense ultraviolet radiation, photoionizing the expanding gas and causing it to glow with brilliant [O III] and H-alpha emission lines.',
    importance: 'Key mechanism enriching the interstellar medium with carbon, nitrogen, and intermediate-mass synthesized elements.',
    relatedTopicIds: ['asymptotic-giant-branch', 'white-dwarf', 'red-giant'],
    tags: ['Nebula', 'Planetary Nebula', 'Photoionization', 'Interstellar Medium'],
  },
  {
    id: 'core-collapse',
    title: 'Gravitational Core Collapse',
    category: 'REMNANTS',
    shortExplanation: 'The sudden implosion of an evolved massive star’s iron core when electron degeneracy fails under nuclear photodisintegration and electron capture.',
    detailedExplanation: 'Iron cannot release energy through fusion. Once the iron core surpasses the Chandrasekhar limit, electrons capture onto protons (e⁻ + p → n + ν_e) and iron nuclei undergo endothermic photodisintegration. Deprived of pressure support, the core implodes at ~70,000 km/s in less than 0.25 seconds until nuclear saturation density halts the fall.',
    importance: 'Triggers the most violent energetic explosions in the modern universe (Type II / Ib / Ic Supernovae).',
    relatedTopicIds: ['supernova', 'neutron-star', 'chandrasekhar-limit'],
    tags: ['Core Collapse', 'Iron Core', 'Implosion', 'Supernova'],
  },
  {
    id: 'supernova',
    title: 'Core-Collapse Supernova (Type II)',
    category: 'REMNANTS',
    shortExplanation: 'A colossal stellar explosion releasing ~10⁴⁴ Joules of kinetic energy and outshining an entire galaxy for weeks.',
    detailedExplanation: 'When the collapsing core reaches nuclear saturation density, the incompressible nuclear strong force causes the inner core to rebound. This generates an outward shockwave, revived by an intense neutrino flux. The explosion rips the star apart at 5,000 - 15,000 km/s, powered by the radioactive decay of synthesized Nickel-56.',
    keyEquation: {
      title: 'Radioactive Light Curve Decay Steps',
      text: '⁵⁶Ni (t_1/2 = 6.1 d) → ⁵⁶Co (t_1/2 = 77.2 d) → ⁵⁶Fe (Stable)',
      variables: [
        { symbol: '⁵⁶Ni', name: 'Nickel-56', unit: 'M☉', description: 'Radioactive isotope synthesized in explosive shockwave.' },
        { symbol: '⁵⁶Co', name: 'Cobalt-56', unit: 'M☉', description: 'Decay intermediate powering the exponential light-curve tail.' },
        { symbol: '⁵⁶Fe', name: 'Iron-56', unit: 'M☉', description: 'Stable end product forming planetary metallic cores.' },
      ],
    },
    importance: 'The cosmic forge creating and distributing the majority of iron, calcium, and heavy elements across the cosmos.',
    relatedTopicIds: ['core-collapse', 'neutron-star', 'black-hole'],
    tags: ['Supernova', 'Explosion', 'Nickel-56', 'Shockwave', 'Nucleosynthesis'],
  },
  {
    id: 'neutron-star',
    title: 'Neutron Star & Pulsar Mechanics',
    category: 'REMNANTS',
    shortExplanation: 'An ultra-dense city-sized stellar remnant supported entirely by neutron degeneracy pressure and nuclear forces.',
    detailedExplanation: 'With a radius of ~11.5 km and a mass of 1.4 - 2.1 M☉, neutron stars have average densities exceeding 3 × 10¹⁷ kg/m³ (a sugar-cube portion weighs ~1 billion tons). Conservation of magnetic flux and angular momentum creates extreme magnetic fields (B ~ 10⁸ - 10¹¹ Tesla) and millisecond rotation periods, producing lighthouse-like pulsar beams.',
    importance: 'Natural high-energy laboratories exhibiting extreme relativistic compactness (Ξ ≈ 0.185) and gravitational wave emissions during mergers.',
    relatedTopicIds: ['tov-limit', 'core-collapse', 'black-hole'],
    tags: ['Neutron Star', 'Pulsar', 'Nuclear Density', 'Relativistic'],
  },
  {
    id: 'tov-limit',
    title: 'Tolman-Oppenheimer-Volkoff (TOV) Limit',
    category: 'REMNANTS',
    shortExplanation: 'The maximum theoretical mass of a non-rotating neutron star (≈ 2.17 - 2.3 M☉) before general relativistic collapse into a black hole.',
    detailedExplanation: 'Analogous to the Chandrasekhar limit for white dwarfs, the TOV limit incorporates general relativistic corrections to hydrostatic balance. When core mass exceeds ~2.17 M☉, even the strong nuclear force and neutron degeneracy cannot halt total gravitational collapse.',
    importance: 'Defines the rigid boundary dividing neutron stars from stellar-mass black holes.',
    relatedTopicIds: ['neutron-star', 'black-hole', 'chandrasekhar-limit'],
    tags: ['TOV Limit', 'Neutron Star Limit', 'General Relativity'],
  },
  {
    id: 'black-hole',
    title: 'Stellar Black Hole & Schwarzschild Geometry',
    category: 'REMNANTS',
    shortExplanation: 'A region of spacetime where gravitational curvature is so extreme that nothing—not even light—can escape.',
    detailedExplanation: 'Formed from hypermassive stars (M_initial ≳ 25 M☉) whose collapsing cores exceed the TOV limit. The mass collapses to a central singularity surrounded by an event horizon at the Schwarzschild radius (r_s = 2GM/c²). Infalling matter forms a superheated accretion disk radiating luminous X-rays.',
    keyEquation: {
      title: 'Schwarzschild Radius',
      text: 'r_s = 2 · G · M / c² ≈ 2.95 km · (M / M☉)',
      variables: [
        { symbol: 'r_s', name: 'Schwarzschild Radius (Event Horizon)', unit: 'meters (m)', description: 'Radius of the non-luminous boundary.' },
        { symbol: 'G', name: 'Gravitational Constant', unit: 'm³/(kg·s²)', description: '6.6743 × 10⁻¹¹.' },
        { symbol: 'M', name: 'Black Hole Mass', unit: 'kg', description: 'Mass enclosed within singularity.' },
        { symbol: 'c', name: 'Speed of Light', unit: 'm/s', description: '299,792,458 m/s.' },
      ],
    },
    importance: 'The ultimate gravitational extreme predicted by Einstein’s General Theory of Relativity.',
    relatedTopicIds: ['tov-limit', 'escape-velocity', 'supernova'],
    tags: ['Black Hole', 'Event Horizon', 'Singularity', 'General Relativity', 'Schwarzschild'],
  },
  {
    id: 'escape-velocity',
    title: 'Escape Velocity & Gravitational Potential',
    category: 'GRAVITY',
    shortExplanation: 'The minimum speed an object must travel to permanently escape the gravitational pull of a massive body without further propulsion.',
    detailedExplanation: 'Derived by equating kinetic energy to gravitational potential energy. For Earth, v_esc is 11.2 km/s. For a neutron star, v_esc reaches ~61% the speed of light. At the event horizon of a black hole, the escape velocity equals the speed of light c.',
    keyEquation: {
      title: 'Escape Velocity Formula',
      text: 'v_esc = √(2 · G · M / R)',
      variables: [
        { symbol: 'v_esc', name: 'Escape Velocity', unit: 'm/s (or km/s)', description: 'Minimum velocity for ballistic escape.' },
        { symbol: 'G', name: 'Gravitational Constant', unit: 'm³/(kg·s²)', description: '6.6743 × 10⁻¹¹.' },
        { symbol: 'M', name: 'Mass of Celestial Body', unit: 'kg', description: 'Total enclosed mass.' },
        { symbol: 'R', name: 'Radius of Celestial Body', unit: 'meters (m)', description: 'Distance from center of mass.' },
      ],
    },
    importance: 'Governs planetary atmosphere retention, orbital spaceflight, and the physical definition of black hole event horizons.',
    relatedTopicIds: ['black-hole', 'neutron-star', 'hydrostatic-equilibrium'],
    tags: ['Escape Velocity', 'Gravity', 'Orbital Mechanics', 'Astrophysics'],
  },
  {
    id: 'hr-diagram',
    title: 'Hertzsprung-Russell (HR) Diagram',
    category: 'STELLAR_STRUCTURE',
    shortExplanation: 'The master diagnostic plot in astronomy, correlating stellar luminosity (or absolute magnitude) with effective surface temperature (or spectral class).',
    detailedExplanation: 'Introduced independently by Ejnar Hertzsprung and Henry Norris Russell in the early 20th century. By plotting stars with temperature decreasing along the horizontal axis (hot blue on left, cool red on right) and luminosity on the vertical axis, stars naturally organize into distinct evolutionary groups: Main Sequence, Subgiants, Giants, Supergiants, and White Dwarfs.',
    importance: 'The definitive tool for determining stellar ages, cluster distances, and testing stellar evolution models.',
    relatedTopicIds: ['stefan-boltzmann', 'main-sequence', 'red-giant', 'spectral-classification'],
    tags: ['HR Diagram', 'Hertzsprung-Russell', 'Spectral Classification', 'Stellar Evolution'],
  },
  {
    id: 'spectral-classification',
    title: 'Morgan-Keenan Spectral Classification',
    category: 'STELLAR_STRUCTURE',
    shortExplanation: 'Astronomical classification scheme (O, B, A, F, G, K, M) categorizing stars based on surface temperature and spectral absorption lines.',
    detailedExplanation: 'Arranged from hottest to coolest: O (> 30,000 K, ionized helium/nitrogen), B (10,000 - 30,000 K, neutral helium), A (7,500 - 10,000 K, strong Balmer hydrogen), F (6,000 - 7,500 K, ionized metals), G (5,200 - 6,000 K, neutral metals, e.g. Sun), K (3,700 - 5,200 K), and M (< 3,700 K, molecular TiO bands). Luminosity classes (I = Supergiant, III = Giant, V = Main Sequence) further define physical size.',
    importance: 'Enables precise remote determination of a star’s temperature, surface gravity, chemical composition, and evolutionary state.',
    relatedTopicIds: ['hr-diagram', 'stefan-boltzmann', 'main-sequence'],
    tags: ['Spectral Class', 'OBAFGKM', 'Absorption Lines', 'Stellar Astronomy'],
  },
  {
    id: 'metallicity',
    title: 'Stellar Metallicity & Chemical Enrichment',
    category: 'COSMOLOGY',
    shortExplanation: 'The abundance of elements heavier than hydrogen and helium (denoted as metals, Z) in a star or interstellar gas cloud.',
    detailedExplanation: 'In astronomy, all elements beyond He are termed "metals." Primordial Population III stars had Z ≈ 0. Successive generations of supernovae, planetary nebulae, and neutron star mergers enrich the interstellar gas with synthesized metals. Modern stars like our Sun (Population I) have Z ≈ 0.014 ([Fe/H] = 0.0), allowing rocky planet formation.',
    keyEquation: {
      title: 'Composition Conservation Law',
      text: 'X + Y + Z = 1.0',
      variables: [
        { symbol: 'X', name: 'Hydrogen Mass Fraction', unit: 'dimensionless', description: 'Fraction of mass in Hydrogen (≈ 0.73 for Sun).' },
        { symbol: 'Y', name: 'Helium Mass Fraction', unit: 'dimensionless', description: 'Fraction of mass in Helium (≈ 0.25 for Sun).' },
        { symbol: 'Z', name: 'Metallicity (Heavy Elements)', unit: 'dimensionless', description: 'Fraction of mass in elements C, N, O, Fe, etc. (≈ 0.014 for Sun).' },
      ],
    },
    importance: 'Dictates the efficiency of rocky planet formation and opacity in stellar atmospheres across cosmic time.',
    relatedTopicIds: ['stellar-fusion', 'supernova', 'asymptotic-giant-branch'],
    tags: ['Metallicity', 'Population I', 'Population II', 'Enrichment', 'Cosmic Chemistry'],
  },
];
